# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.7.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class BankTemplateImportResponse(BaseModel):
    """
    Response model for the bank template import endpoint.
    """ # noqa: E501
    bank_id: StrictStr = Field(description="Bank that was imported into")
    config_applied: StrictBool = Field(description="Whether bank config was updated")
    mental_models_created: Optional[List[StrictStr]] = Field(default=None, description="IDs of newly created mental models")
    mental_models_updated: Optional[List[StrictStr]] = Field(default=None, description="IDs of updated mental models")
    directives_created: Optional[List[StrictStr]] = Field(default=None, description="Names of newly created directives")
    directives_updated: Optional[List[StrictStr]] = Field(default=None, description="Names of updated directives")
    operation_ids: Optional[List[StrictStr]] = Field(default=None, description="Operation IDs for mental model content generation (async)")
    dry_run: Optional[StrictBool] = Field(default=False, description="True if this was a validation-only run")
    __properties: ClassVar[List[str]] = ["bank_id", "config_applied", "mental_models_created", "mental_models_updated", "directives_created", "directives_updated", "operation_ids", "dry_run"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BankTemplateImportResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BankTemplateImportResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bank_id": obj.get("bank_id"),
            "config_applied": obj.get("config_applied"),
            "mental_models_created": obj.get("mental_models_created"),
            "mental_models_updated": obj.get("mental_models_updated"),
            "directives_created": obj.get("directives_created"),
            "directives_updated": obj.get("directives_updated"),
            "operation_ids": obj.get("operation_ids"),
            "dry_run": obj.get("dry_run") if obj.get("dry_run") is not None else False
        })
        return _obj


