# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class LlmOperationHealth(BaseModel):
    """
    LLM connectivity status for a single operation. Status only — no provider/model/ endpoint/error, so the probe never discloses the LLM configuration.
    """ # noqa: E501
    operation: StrictStr = Field(description="Operation whose LLM was probed")
    ok: StrictBool = Field(description="True only when the probe connected successfully")
    status: StrictStr = Field(description="'connected'; 'not_configured' (provider is 'none'); 'auth_failed' (rejected — usually a wrong/expired API key); 'unreachable' (call failed); 'timeout'")
    latency_ms: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["operation", "ok", "status", "latency_ms"]

    @field_validator('operation')
    def operation_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['retain', 'consolidation', 'reflect']):
            raise ValueError("must be one of enum values ('retain', 'consolidation', 'reflect')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['connected', 'not_configured', 'auth_failed', 'unreachable', 'timeout']):
            raise ValueError("must be one of enum values ('connected', 'not_configured', 'auth_failed', 'unreachable', 'timeout')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LlmOperationHealth from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if latency_ms (nullable) is None
        # and model_fields_set contains the field
        if self.latency_ms is None and "latency_ms" in self.model_fields_set:
            _dict['latency_ms'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LlmOperationHealth from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "operation": obj.get("operation"),
            "ok": obj.get("ok"),
            "status": obj.get("status"),
            "latency_ms": obj.get("latency_ms")
        })
        return _obj


