# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from hindsight_client_api.models.tag_group_leaf import TagGroupLeaf
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

MENTALMODELTRIGGERINPUTTAGGROUPSINNER_ANY_OF_SCHEMAS = ["TagGroupAndInput", "TagGroupLeaf", "TagGroupNotInput", "TagGroupOrInput"]

class MentalModelTriggerInputTagGroupsInner(BaseModel):
    """
    MentalModelTriggerInputTagGroupsInner
    """

    # data type: TagGroupLeaf
    anyof_schema_1_validator: Optional[TagGroupLeaf] = None
    # data type: TagGroupAndInput
    anyof_schema_2_validator: Optional[TagGroupAndInput] = None
    # data type: TagGroupOrInput
    anyof_schema_3_validator: Optional[TagGroupOrInput] = None
    # data type: TagGroupNotInput
    anyof_schema_4_validator: Optional[TagGroupNotInput] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[TagGroupAndInput, TagGroupLeaf, TagGroupNotInput, TagGroupOrInput]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "TagGroupAndInput", "TagGroupLeaf", "TagGroupNotInput", "TagGroupOrInput" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = MentalModelTriggerInputTagGroupsInner.model_construct()
        error_messages = []
        # validate data type: TagGroupLeaf
        if not isinstance(v, TagGroupLeaf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TagGroupLeaf`")
        else:
            return v

        # validate data type: TagGroupAndInput
        if not isinstance(v, TagGroupAndInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TagGroupAndInput`")
        else:
            return v

        # validate data type: TagGroupOrInput
        if not isinstance(v, TagGroupOrInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TagGroupOrInput`")
        else:
            return v

        # validate data type: TagGroupNotInput
        if not isinstance(v, TagGroupNotInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TagGroupNotInput`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in MentalModelTriggerInputTagGroupsInner with anyOf schemas: TagGroupAndInput, TagGroupLeaf, TagGroupNotInput, TagGroupOrInput. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[TagGroupLeaf] = None
        try:
            instance.actual_instance = TagGroupLeaf.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[TagGroupAndInput] = None
        try:
            instance.actual_instance = TagGroupAndInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[TagGroupOrInput] = None
        try:
            instance.actual_instance = TagGroupOrInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[TagGroupNotInput] = None
        try:
            instance.actual_instance = TagGroupNotInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into MentalModelTriggerInputTagGroupsInner with anyOf schemas: TagGroupAndInput, TagGroupLeaf, TagGroupNotInput, TagGroupOrInput. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], TagGroupAndInput, TagGroupLeaf, TagGroupNotInput, TagGroupOrInput]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())

from hindsight_client_api.models.tag_group_and_input import TagGroupAndInput
from hindsight_client_api.models.tag_group_not_input import TagGroupNotInput
from hindsight_client_api.models.tag_group_or_input import TagGroupOrInput
# TODO: Rewrite to not use raise_errors
MentalModelTriggerInputTagGroupsInner.model_rebuild(raise_errors=False)

