# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hindsight_client_api.models.operation_progress import OperationProgress
from typing import Optional, Set
from typing_extensions import Self

class OperationResponse(BaseModel):
    """
    Response model for a single async operation.
    """ # noqa: E501
    id: StrictStr
    task_type: StrictStr
    items_count: StrictInt
    document_id: Optional[StrictStr] = None
    created_at: StrictStr
    updated_at: Optional[StrictStr] = None
    status: StrictStr
    error_message: Optional[StrictStr]
    retry_count: Optional[StrictInt] = None
    next_retry_at: Optional[StrictStr] = None
    progress: Optional[OperationProgress] = None
    __properties: ClassVar[List[str]] = ["id", "task_type", "items_count", "document_id", "created_at", "updated_at", "status", "error_message", "retry_count", "next_retry_at", "progress"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OperationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of progress
        if self.progress:
            _dict['progress'] = self.progress.to_dict()
        # set to None if document_id (nullable) is None
        # and model_fields_set contains the field
        if self.document_id is None and "document_id" in self.model_fields_set:
            _dict['document_id'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['error_message'] = None

        # set to None if retry_count (nullable) is None
        # and model_fields_set contains the field
        if self.retry_count is None and "retry_count" in self.model_fields_set:
            _dict['retry_count'] = None

        # set to None if next_retry_at (nullable) is None
        # and model_fields_set contains the field
        if self.next_retry_at is None and "next_retry_at" in self.model_fields_set:
            _dict['next_retry_at'] = None

        # set to None if progress (nullable) is None
        # and model_fields_set contains the field
        if self.progress is None and "progress" in self.model_fields_set:
            _dict['progress'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OperationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "task_type": obj.get("task_type"),
            "items_count": obj.get("items_count"),
            "document_id": obj.get("document_id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "status": obj.get("status"),
            "error_message": obj.get("error_message"),
            "retry_count": obj.get("retry_count"),
            "next_retry_at": obj.get("next_retry_at"),
            "progress": OperationProgress.from_dict(obj["progress"]) if obj.get("progress") is not None else None
        })
        return _obj


