# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from hindsight_client_api.models.budget import Budget
from hindsight_client_api.models.mental_model_trigger_input_tag_groups_inner import MentalModelTriggerInputTagGroupsInner
from hindsight_client_api.models.reflect_include_options import ReflectIncludeOptions
from typing import Optional, Set
from typing_extensions import Self

class ReflectRequest(BaseModel):
    """
    Request model for reflect endpoint.
    """ # noqa: E501
    query: StrictStr
    budget: Optional[Budget] = None
    context: Optional[StrictStr] = None
    max_tokens: Optional[StrictInt] = Field(default=4096, description="Maximum tokens for the response")
    include: Optional[ReflectIncludeOptions] = Field(default=None, description="Options for including additional data (disabled by default)")
    response_schema: Optional[Dict[str, Any]] = None
    tags: Optional[List[StrictStr]] = None
    tags_match: Optional[StrictStr] = Field(default='any', description="How to match tags: 'any' (OR, includes untagged), 'all' (AND, includes untagged), 'any_strict' (OR, excludes untagged), 'all_strict' (AND, excludes untagged).")
    tag_groups: Optional[List[MentalModelTriggerInputTagGroupsInner]] = None
    fact_types: Optional[List[StrictStr]] = None
    exclude_mental_models: Optional[StrictBool] = Field(default=False, description="If true, exclude all mental models from the reflect loop (skip search_mental_models tool).")
    exclude_mental_model_ids: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["query", "budget", "context", "max_tokens", "include", "response_schema", "tags", "tags_match", "tag_groups", "fact_types", "exclude_mental_models", "exclude_mental_model_ids"]

    @field_validator('tags_match')
    def tags_match_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['any', 'all', 'any_strict', 'all_strict', 'exact']):
            raise ValueError("must be one of enum values ('any', 'all', 'any_strict', 'all_strict', 'exact')")
        return value

    @field_validator('fact_types')
    def fact_types_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['world', 'experience', 'observation']):
                raise ValueError("each list item must be one of ('world', 'experience', 'observation')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReflectRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of include
        if self.include:
            _dict['include'] = self.include.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tag_groups (list)
        _items = []
        if self.tag_groups:
            for _item_tag_groups in self.tag_groups:
                if _item_tag_groups:
                    _items.append(_item_tag_groups.to_dict())
            _dict['tag_groups'] = _items
        # set to None if context (nullable) is None
        # and model_fields_set contains the field
        if self.context is None and "context" in self.model_fields_set:
            _dict['context'] = None

        # set to None if response_schema (nullable) is None
        # and model_fields_set contains the field
        if self.response_schema is None and "response_schema" in self.model_fields_set:
            _dict['response_schema'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        # set to None if tag_groups (nullable) is None
        # and model_fields_set contains the field
        if self.tag_groups is None and "tag_groups" in self.model_fields_set:
            _dict['tag_groups'] = None

        # set to None if fact_types (nullable) is None
        # and model_fields_set contains the field
        if self.fact_types is None and "fact_types" in self.model_fields_set:
            _dict['fact_types'] = None

        # set to None if exclude_mental_model_ids (nullable) is None
        # and model_fields_set contains the field
        if self.exclude_mental_model_ids is None and "exclude_mental_model_ids" in self.model_fields_set:
            _dict['exclude_mental_model_ids'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReflectRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "query": obj.get("query"),
            "budget": obj.get("budget"),
            "context": obj.get("context"),
            "max_tokens": obj.get("max_tokens") if obj.get("max_tokens") is not None else 4096,
            "include": ReflectIncludeOptions.from_dict(obj["include"]) if obj.get("include") is not None else None,
            "response_schema": obj.get("response_schema"),
            "tags": obj.get("tags"),
            "tags_match": obj.get("tags_match") if obj.get("tags_match") is not None else 'any',
            "tag_groups": [MentalModelTriggerInputTagGroupsInner.from_dict(_item) for _item in obj["tag_groups"]] if obj.get("tag_groups") is not None else None,
            "fact_types": obj.get("fact_types"),
            "exclude_mental_models": obj.get("exclude_mental_models") if obj.get("exclude_mental_models") is not None else False,
            "exclude_mental_model_ids": obj.get("exclude_mental_model_ids")
        })
        return _obj


