"""Move mental-model and observation history into dedicated tables.

Both histories were accumulated in a single JSONB/CLOB ``history`` column
(``mental_models.history`` and ``memory_units.history``), appended to on every
update. That design has two problems:

1. **Unbounded growth on observations.** The observation write path appended a
   snapshot on every update with no cap at all, so a frequently-reinforced
   observation grew its ``history`` array until it crossed Postgres's hard 256MB
   jsonb limit (SQLSTATE 54000), after which every further UPDATE failed and the
   row was stuck.
2. **Wrong-axis cap on mental models.** The mental-model cap bounded the *number*
   of entries (50), not their *size* — a single large reflect snapshot could
   still blow the budget — and rewrote the whole array (plus TOAST) on every
   refresh, defeating HOT updates.

This migration creates one row per history entry in two dedicated tables, with
an index that makes "most recent N for this item" cheap, then drops the old
columns. The cap is now enforced at write time as a bounded DELETE of the
oldest over-cap rows (see config ``*_HISTORY_MAX_ENTRIES``).

Revision ID: a7b8c9d0e1f2
Revises: d3e4f5a6b7c8
Create Date: 2026-06-05
"""

from collections.abc import Sequence

from alembic import context, op

from hindsight_api.alembic._dialect import run_for_dialect

revision: str = "a7b8c9d0e1f2"
down_revision: str | Sequence[str] | None = "d3e4f5a6b7c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _get_schema_prefix() -> str:
    """Schema-qualifier for raw SQL on PG (multi-tenant search_path)."""
    schema = context.config.get_main_option("target_schema")
    return f'"{schema}".' if schema else ""


# ---------------------------------------------------------------------------
# PostgreSQL
# ---------------------------------------------------------------------------
def _pg_upgrade() -> None:
    schema = _get_schema_prefix()

    # Both tables share the same shape: surrogate id, FK to the parent, bank_id,
    # the snapshot payload as a single JSONB ``content`` blob, and changed_at.
    # The payload is per-row (one change per row) so it stays small — this is NOT
    # the old single-column-grows-forever design; growth is bounded by row count
    # plus the write-time cap. Folding the previous_* fields into one JSONB keeps
    # the schema dialect-simple (no array columns) and flexible.

    # --- mental_model_history -------------------------------------------------
    # content: {"previous_content": ..., "previous_reflect_response": {...}}
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {schema}mental_model_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            mental_model_id VARCHAR(64) NOT NULL,
            bank_id TEXT NOT NULL,
            content JSONB NOT NULL,
            changed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
            FOREIGN KEY (mental_model_id, bank_id)
                REFERENCES {schema}mental_models(id, bank_id) ON DELETE CASCADE
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_mm_history_model "
        f"ON {schema}mental_model_history (bank_id, mental_model_id, changed_at DESC, id DESC)"
    )

    # --- observation_history --------------------------------------------------
    # content: {"previous_text", "previous_tags", "previous_occurred_start",
    #           "previous_occurred_end", "previous_mentioned_at", "new_source_memory_ids"}
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {schema}observation_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            observation_id UUID NOT NULL,
            bank_id TEXT NOT NULL,
            content JSONB NOT NULL,
            changed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
            FOREIGN KEY (observation_id)
                REFERENCES {schema}memory_units(id) ON DELETE CASCADE
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_observation_history_obs "
        f"ON {schema}observation_history (observation_id, changed_at DESC, id DESC)"
    )

    # --- backfill mental models ----------------------------------------------
    # Explode each row's history array into rows, preserving chronological order
    # via WITH ORDINALITY so the IDENTITY id tie-breaks oldest->newest correctly.
    # changed_at is promoted to its own column; the rest of the element becomes
    # ``content`` (the ``- 'changed_at'`` strips the now-redundant key).
    op.execute(
        f"""
        INSERT INTO {schema}mental_model_history (mental_model_id, bank_id, content, changed_at)
        SELECT mm.id, mm.bank_id,
               e - 'changed_at',
               COALESCE(NULLIF(e->>'changed_at', '')::timestamptz, now())
        FROM {schema}mental_models mm
             CROSS JOIN LATERAL jsonb_array_elements(mm.history) WITH ORDINALITY a(e, ord)
        WHERE mm.history IS NOT NULL
          AND jsonb_typeof(mm.history) = 'array'
          AND jsonb_array_length(mm.history) > 0
        ORDER BY mm.id, mm.bank_id, ord
        """
    )

    # --- backfill observations -----------------------------------------------
    op.execute(
        f"""
        INSERT INTO {schema}observation_history (observation_id, bank_id, content, changed_at)
        SELECT mu.id, mu.bank_id,
               e - 'changed_at',
               COALESCE(NULLIF(e->>'changed_at', '')::timestamptz, now())
        FROM {schema}memory_units mu
             CROSS JOIN LATERAL jsonb_array_elements(mu.history) WITH ORDINALITY a(e, ord)
        WHERE mu.fact_type = 'observation'
          AND mu.history IS NOT NULL
          AND jsonb_typeof(mu.history) = 'array'
          AND jsonb_array_length(mu.history) > 0
        ORDER BY mu.id, ord
        """
    )

    # --- drop the legacy columns ---------------------------------------------
    op.execute(f"ALTER TABLE {schema}mental_models DROP COLUMN IF EXISTS history")
    op.execute(f"ALTER TABLE {schema}memory_units DROP COLUMN IF EXISTS history")


def _pg_downgrade() -> None:
    schema = _get_schema_prefix()

    # Re-add the columns (empty — historical content is not reconstructed back
    # into the array form; the dedicated tables are dropped below).
    op.execute(f"ALTER TABLE {schema}mental_models ADD COLUMN IF NOT EXISTS history JSONB DEFAULT '[]'::jsonb")
    op.execute(f"ALTER TABLE {schema}memory_units ADD COLUMN IF NOT EXISTS history JSONB DEFAULT '[]'::jsonb")

    op.execute(f"DROP INDEX IF EXISTS {schema}idx_observation_history_obs")
    op.execute(f"DROP TABLE IF EXISTS {schema}observation_history")
    op.execute(f"DROP INDEX IF EXISTS {schema}idx_mm_history_model")
    op.execute(f"DROP TABLE IF EXISTS {schema}mental_model_history")


# ---------------------------------------------------------------------------
# Oracle 23ai
# ---------------------------------------------------------------------------
def _oracle_upgrade() -> None:
    # Same single-JSONB shape as PG: ``content`` holds the snapshot payload as a
    # CLOB IS JSON. The legacy per-element JSON object (minus changed_at, promoted
    # to its own column) is carried through verbatim on backfill — the array
    # columns the previous design needed are gone.
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS mental_model_history (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY,
            mental_model_id VARCHAR2(256) NOT NULL,
            bank_id VARCHAR2(256) NOT NULL,
            content CLOB NOT NULL
                CONSTRAINT mmh_content_json CHECK (content IS JSON),
            changed_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT pk_mental_model_history PRIMARY KEY (id),
            CONSTRAINT fk_mmh_model FOREIGN KEY (mental_model_id, bank_id)
                REFERENCES mental_models(id, bank_id) ON DELETE CASCADE
        )
        """
    )
    op.execute(
        "CREATE INDEX idx_mm_history_model ON mental_model_history (bank_id, mental_model_id, changed_at DESC, id DESC)"
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS observation_history (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY,
            observation_id RAW(16) NOT NULL,
            bank_id VARCHAR2(256) NOT NULL,
            content CLOB NOT NULL
                CONSTRAINT oh_content_json CHECK (content IS JSON),
            changed_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT pk_observation_history PRIMARY KEY (id),
            CONSTRAINT fk_oh_obs FOREIGN KEY (observation_id)
                REFERENCES memory_units(id) ON DELETE CASCADE
        )
        """
    )
    op.execute(
        "CREATE INDEX idx_observation_history_obs ON observation_history (observation_id, changed_at DESC, id DESC)"
    )

    bind = op.get_bind()

    # Backfill via JSON_TABLE. ``content`` is the whole element (FORMAT JSON PATH
    # '$'); changed_at is also promoted to its own column. Backfilled content may
    # therefore still carry a redundant changed_at key, which the read path
    # ignores in favour of the column — harmless, and avoids JSON surgery here.
    bind.exec_driver_sql(
        """
        INSERT INTO mental_model_history (mental_model_id, bank_id, content, changed_at)
        SELECT mm.id, mm.bank_id, jt.content, NVL(jt.changed_at, SYSTIMESTAMP)
        FROM mental_models mm,
             JSON_TABLE(mm.history, '$[*]' COLUMNS (
                 seq FOR ORDINALITY,
                 content CLOB FORMAT JSON PATH '$',
                 changed_at TIMESTAMP WITH TIME ZONE PATH '$.changed_at'
             )) jt
        WHERE mm.history IS NOT NULL
        ORDER BY mm.id, mm.bank_id, jt.seq
        """
    )

    bind.exec_driver_sql(
        """
        INSERT INTO observation_history (observation_id, bank_id, content, changed_at)
        SELECT mu.id, mu.bank_id, jt.content, NVL(jt.changed_at, SYSTIMESTAMP)
        FROM memory_units mu,
             JSON_TABLE(mu.history, '$[*]' COLUMNS (
                 seq FOR ORDINALITY,
                 content CLOB FORMAT JSON PATH '$',
                 changed_at TIMESTAMP WITH TIME ZONE PATH '$.changed_at'
             )) jt
        WHERE mu.fact_type = 'observation' AND mu.history IS NOT NULL
        ORDER BY mu.id, jt.seq
        """
    )

    op.execute("ALTER TABLE mental_models DROP COLUMN history")
    op.execute("ALTER TABLE memory_units DROP COLUMN history")


def _oracle_downgrade() -> None:
    op.execute("ALTER TABLE mental_models ADD history CLOB DEFAULT '[]' NOT NULL")
    op.execute("ALTER TABLE memory_units ADD history CLOB DEFAULT '[]'")
    op.execute("DROP TABLE observation_history CASCADE CONSTRAINTS")
    op.execute("DROP TABLE mental_model_history CASCADE CONSTRAINTS")


def upgrade() -> None:
    run_for_dialect(pg=_pg_upgrade, oracle=_oracle_upgrade)


def downgrade() -> None:
    run_for_dialect(pg=_pg_downgrade, oracle=_oracle_downgrade)
