"""Render an embed ``.env`` config seeded from the bundled ``.env.example``.

``hindsight-embed configure`` and profile creation used to write a bare,
four-key file. Seeding from the same ``.env.example`` shipped in the repo gives
users the full, documented set of options as commented references while keeping
the values they actually configured active.
"""

from __future__ import annotations

import importlib.resources
from pathlib import Path


def load_template() -> str | None:
    """Return the ``.env.example`` template text, or ``None`` if not found.

    Prefers the copy bundled inside the package (the only one present for
    ``pip``/``uvx`` installs); falls back to the repo-root ``.env.example`` in a
    source checkout.
    """
    bundled = importlib.resources.files("hindsight_embed").joinpath("env.example")
    if bundled.is_file():
        return bundled.read_text()
    for parent in Path(__file__).resolve().parents:
        candidate = parent / ".env.example"
        if candidate.is_file():
            return candidate.read_text()
    return None


def _line_key(line: str) -> str | None:
    """Return the env-var key of an active ``KEY=VALUE`` line, else ``None``."""
    stripped = line.strip()
    if not stripped or stripped.startswith("#") or "=" not in stripped:
        return None
    if stripped.startswith("export "):
        stripped = stripped[7:]
    return stripped.split("=", 1)[0].strip()


def render_config(values: dict[str, str], template: str | None = None) -> str:
    """Render an embed ``.env`` from the template with ``values`` applied.

    Everything is commented out by default: only the keys the user explicitly
    set are active. The template ships active api-server defaults (e.g.
    ``HINDSIGHT_API_PORT=8888``, an OpenAI base URL) that the embed daemon
    manages itself or that are provider-specific; applying them would collide
    profiles on a port or force the wrong base URL, so they stay as commented
    documentation unless the user provides them.

    - Active template assignments for a key in ``values`` are replaced in place.
    - Every other active template assignment is commented out.
    - Keys in ``values`` with no template line are appended in a trailing block.
    - Comments and blank lines are preserved verbatim.

    Falls back to a minimal generated file when no template is available.
    """
    if template is None:
        template = load_template()
    if template is None:
        return _render_minimal(values)

    remaining = dict(values)
    out: list[str] = []
    for line in template.splitlines():
        key = _line_key(line)
        if key is None:
            out.append(line)
        elif key in remaining:
            out.append(f"{key}={remaining.pop(key)}")
        else:
            out.append(f"# {line}")

    if remaining:
        out.append("")
        out.append("# Hindsight Embed settings")
        out.extend(f"{key}={value}" for key, value in remaining.items())

    return "\n".join(out) + "\n"


def _render_minimal(values: dict[str, str]) -> str:
    """Bare fallback used only when the template cannot be located."""
    lines = [
        "# Hindsight Embed Configuration",
        "# Generated by hindsight-embed configure",
        "",
    ]
    lines.extend(f"{key}={value}" for key, value in values.items())
    return "\n".join(lines) + "\n"
