# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_create_webhook(self) -> None:
        """Test case for create_webhook

        Register webhook
        """
        pass

    def test_delete_webhook(self) -> None:
        """Test case for delete_webhook

        Delete webhook
        """
        pass

    def test_list_webhook_deliveries(self) -> None:
        """Test case for list_webhook_deliveries

        List webhook deliveries
        """
        pass

    def test_list_webhooks(self) -> None:
        """Test case for list_webhooks

        List webhooks
        """
        pass

    def test_update_webhook(self) -> None:
        """Test case for update_webhook

        Update webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
