# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.models.entity_list_item import EntityListItem

class TestEntityListItem(unittest.TestCase):
    """EntityListItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntityListItem:
        """Test EntityListItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntityListItem`
        """
        model = EntityListItem()
        if include_optional:
            return EntityListItem(
                id = '',
                canonical_name = '',
                mention_count = 56,
                first_seen = '',
                last_seen = '',
                metadata = {
                    'key' : null
                    }
            )
        else:
            return EntityListItem(
                id = '',
                canonical_name = '',
                mention_count = 56,
        )
        """

    def testEntityListItem(self):
        """Test EntityListItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
