# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.models.webhook_delivery_list_response import WebhookDeliveryListResponse

class TestWebhookDeliveryListResponse(unittest.TestCase):
    """WebhookDeliveryListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookDeliveryListResponse:
        """Test WebhookDeliveryListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookDeliveryListResponse`
        """
        model = WebhookDeliveryListResponse()
        if include_optional:
            return WebhookDeliveryListResponse(
                items = [
                    hindsight_client_api.models.webhook_delivery_response.WebhookDeliveryResponse(
                        id = '', 
                        webhook_id = '', 
                        url = '', 
                        event_type = '', 
                        status = '', 
                        attempts = 56, 
                        next_retry_at = '', 
                        last_error = '', 
                        last_response_status = 56, 
                        last_response_body = '', 
                        last_attempt_at = '', 
                        created_at = '', 
                        updated_at = '', )
                    ],
                next_cursor = ''
            )
        else:
            return WebhookDeliveryListResponse(
                items = [
                    hindsight_client_api.models.webhook_delivery_response.WebhookDeliveryResponse(
                        id = '', 
                        webhook_id = '', 
                        url = '', 
                        event_type = '', 
                        status = '', 
                        attempts = 56, 
                        next_retry_at = '', 
                        last_error = '', 
                        last_response_status = 56, 
                        last_response_body = '', 
                        last_attempt_at = '', 
                        created_at = '', 
                        updated_at = '', )
                    ],
        )
        """

    def testWebhookDeliveryListResponse(self):
        """Test WebhookDeliveryListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
