# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.models.list_documents_response import ListDocumentsResponse

class TestListDocumentsResponse(unittest.TestCase):
    """ListDocumentsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListDocumentsResponse:
        """Test ListDocumentsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListDocumentsResponse`
        """
        model = ListDocumentsResponse()
        if include_optional:
            return ListDocumentsResponse(
                items = [
                    {
                        'key' : null
                        }
                    ],
                total = 56,
                limit = 56,
                offset = 56
            )
        else:
            return ListDocumentsResponse(
                items = [
                    {
                        'key' : null
                        }
                    ],
                total = 56,
                limit = 56,
                offset = 56,
        )
        """

    def testListDocumentsResponse(self):
        """Test ListDocumentsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
