# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.models.list_tags_response import ListTagsResponse

class TestListTagsResponse(unittest.TestCase):
    """ListTagsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListTagsResponse:
        """Test ListTagsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListTagsResponse`
        """
        model = ListTagsResponse()
        if include_optional:
            return ListTagsResponse(
                items = [
                    hindsight_client_api.models.tag_item.TagItem(
                        tag = '', 
                        count = 56, )
                    ],
                total = 56,
                limit = 56,
                offset = 56
            )
        else:
            return ListTagsResponse(
                items = [
                    hindsight_client_api.models.tag_item.TagItem(
                        tag = '', 
                        count = 56, )
                    ],
                total = 56,
                limit = 56,
                offset = 56,
        )
        """

    def testListTagsResponse(self):
        """Test ListTagsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
