# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.models.retain_request import RetainRequest

class TestRetainRequest(unittest.TestCase):
    """RetainRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RetainRequest:
        """Test RetainRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RetainRequest`
        """
        model = RetainRequest()
        if include_optional:
            return RetainRequest(
                items = [
                    {content=Alice mentioned she's working on a new ML model, context=team meeting, document_id=meeting_notes_2024_01_15, entities=[{text=Alice}, {text=ML model, type=CONCEPT}], metadata={channel=engineering, source=slack}, tags=[user_a, user_b], timestamp=2024-01-15T10:30:00Z}
                    ],
                var_async = True,
                document_tags = [
                    ''
                    ]
            )
        else:
            return RetainRequest(
                items = [
                    {content=Alice mentioned she's working on a new ML model, context=team meeting, document_id=meeting_notes_2024_01_15, entities=[{text=Alice}, {text=ML model, type=CONCEPT}], metadata={channel=engineering, source=slack}, tags=[user_a, user_b], timestamp=2024-01-15T10:30:00Z}
                    ],
        )
        """

    def testRetainRequest(self):
        """Test RetainRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
