# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.models.add_background_request import AddBackgroundRequest

class TestAddBackgroundRequest(unittest.TestCase):
    """AddBackgroundRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddBackgroundRequest:
        """Test AddBackgroundRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddBackgroundRequest`
        """
        model = AddBackgroundRequest()
        if include_optional:
            return AddBackgroundRequest(
                content = '',
                update_disposition = True
            )
        else:
            return AddBackgroundRequest(
                content = '',
        )
        """

    def testAddBackgroundRequest(self):
        """Test AddBackgroundRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
