# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.models.document_import_submit_response import DocumentImportSubmitResponse

class TestDocumentImportSubmitResponse(unittest.TestCase):
    """DocumentImportSubmitResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentImportSubmitResponse:
        """Test DocumentImportSubmitResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentImportSubmitResponse`
        """
        model = DocumentImportSubmitResponse()
        if include_optional:
            return DocumentImportSubmitResponse(
                operation_id = '',
                status = 'pending'
            )
        else:
            return DocumentImportSubmitResponse(
                operation_id = '',
        )
        """

    def testDocumentImportSubmitResponse(self):
        """Test DocumentImportSubmitResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
