# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.models.include_options import IncludeOptions

class TestIncludeOptions(unittest.TestCase):
    """IncludeOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IncludeOptions:
        """Test IncludeOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IncludeOptions`
        """
        model = IncludeOptions()
        if include_optional:
            return IncludeOptions(
                entities = hindsight_client_api.models.entity_include_options.EntityIncludeOptions(
                    max_tokens = 56, ),
                chunks = hindsight_client_api.models.chunk_include_options.ChunkIncludeOptions(
                    max_tokens = 56, ),
                source_facts = hindsight_client_api.models.source_facts_include_options.SourceFactsIncludeOptions(
                    max_tokens = 56, 
                    max_tokens_per_observation = 56, )
            )
        else:
            return IncludeOptions(
        )
        """

    def testIncludeOptions(self):
        """Test IncludeOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
