# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.models.update_webhook_request import UpdateWebhookRequest

class TestUpdateWebhookRequest(unittest.TestCase):
    """UpdateWebhookRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWebhookRequest:
        """Test UpdateWebhookRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWebhookRequest`
        """
        model = UpdateWebhookRequest()
        if include_optional:
            return UpdateWebhookRequest(
                url = '',
                secret = '',
                event_types = [
                    ''
                    ],
                enabled = True,
                http_config = hindsight_client_api.models.webhook_http_config.WebhookHttpConfig(
                    method = 'POST', 
                    timeout_seconds = 56, 
                    headers = {
                        'key' : ''
                        }, 
                    params = {
                        'key' : ''
                        }, )
            )
        else:
            return UpdateWebhookRequest(
        )
        """

    def testUpdateWebhookRequest(self):
        """Test UpdateWebhookRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
