# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.models.entity_list_response import EntityListResponse

class TestEntityListResponse(unittest.TestCase):
    """EntityListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntityListResponse:
        """Test EntityListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntityListResponse`
        """
        model = EntityListResponse()
        if include_optional:
            return EntityListResponse(
                items = [
                    {canonical_name=John, first_seen=2024-01-15T10:30:00Z, id=123e4567-e89b-12d3-a456-426614174000, last_seen=2024-02-01T14:00:00Z, mention_count=15}
                    ],
                total = 56,
                limit = 56,
                offset = 56
            )
        else:
            return EntityListResponse(
                items = [
                    {canonical_name=John, first_seen=2024-01-15T10:30:00Z, id=123e4567-e89b-12d3-a456-426614174000, last_seen=2024-02-01T14:00:00Z, mention_count=15}
                    ],
                total = 56,
                limit = 56,
                offset = 56,
        )
        """

    def testEntityListResponse(self):
        """Test EntityListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
