# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.models.delete_response import DeleteResponse

class TestDeleteResponse(unittest.TestCase):
    """DeleteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteResponse:
        """Test DeleteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteResponse`
        """
        model = DeleteResponse()
        if include_optional:
            return DeleteResponse(
                success = True,
                message = '',
                deleted_count = 56
            )
        else:
            return DeleteResponse(
                success = True,
        )
        """

    def testDeleteResponse(self):
        """Test DeleteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
