/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ObservationScope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObservationScope{}

// ObservationScope A distinct observation scope: an exact tag set plus its observation count.
type ObservationScope struct {
	// The exact tag set defining this scope (normalized order). Empty list is the global/untagged scope.
	Tags []string `json:"tags"`
	// Number of observations that live under this scope
	Count int32 `json:"count"`
}

type _ObservationScope ObservationScope

// NewObservationScope instantiates a new ObservationScope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObservationScope(tags []string, count int32) *ObservationScope {
	this := ObservationScope{}
	this.Tags = tags
	this.Count = count
	return &this
}

// NewObservationScopeWithDefaults instantiates a new ObservationScope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObservationScopeWithDefaults() *ObservationScope {
	this := ObservationScope{}
	return &this
}

// GetTags returns the Tags field value
func (o *ObservationScope) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *ObservationScope) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *ObservationScope) SetTags(v []string) {
	o.Tags = v
}

// GetCount returns the Count field value
func (o *ObservationScope) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ObservationScope) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ObservationScope) SetCount(v int32) {
	o.Count = v
}

func (o ObservationScope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObservationScope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tags"] = o.Tags
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *ObservationScope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tags",
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObservationScope := _ObservationScope{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varObservationScope)

	if err != nil {
		return err
	}

	*o = ObservationScope(varObservationScope)

	return err
}

type NullableObservationScope struct {
	value *ObservationScope
	isSet bool
}

func (v NullableObservationScope) Get() *ObservationScope {
	return v.value
}

func (v *NullableObservationScope) Set(val *ObservationScope) {
	v.value = val
	v.isSet = true
}

func (v NullableObservationScope) IsSet() bool {
	return v.isSet
}

func (v *NullableObservationScope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObservationScope(val *ObservationScope) *NullableObservationScope {
	return &NullableObservationScope{value: val, isSet: true}
}

func (v NullableObservationScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObservationScope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


