/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.7.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the ChunkIncludeOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChunkIncludeOptions{}

// ChunkIncludeOptions Options for including chunks in recall results.
type ChunkIncludeOptions struct {
	// Maximum tokens for chunks (chunks may be truncated)
	MaxTokens *int32 `json:"max_tokens,omitempty"`
}

// NewChunkIncludeOptions instantiates a new ChunkIncludeOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChunkIncludeOptions() *ChunkIncludeOptions {
	this := ChunkIncludeOptions{}
	var maxTokens int32 = 8192
	this.MaxTokens = &maxTokens
	return &this
}

// NewChunkIncludeOptionsWithDefaults instantiates a new ChunkIncludeOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChunkIncludeOptionsWithDefaults() *ChunkIncludeOptions {
	this := ChunkIncludeOptions{}
	var maxTokens int32 = 8192
	this.MaxTokens = &maxTokens
	return &this
}

// GetMaxTokens returns the MaxTokens field value if set, zero value otherwise.
func (o *ChunkIncludeOptions) GetMaxTokens() int32 {
	if o == nil || IsNil(o.MaxTokens) {
		var ret int32
		return ret
	}
	return *o.MaxTokens
}

// GetMaxTokensOk returns a tuple with the MaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChunkIncludeOptions) GetMaxTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxTokens) {
		return nil, false
	}
	return o.MaxTokens, true
}

// HasMaxTokens returns a boolean if a field has been set.
func (o *ChunkIncludeOptions) HasMaxTokens() bool {
	if o != nil && !IsNil(o.MaxTokens) {
		return true
	}

	return false
}

// SetMaxTokens gets a reference to the given int32 and assigns it to the MaxTokens field.
func (o *ChunkIncludeOptions) SetMaxTokens(v int32) {
	o.MaxTokens = &v
}

func (o ChunkIncludeOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChunkIncludeOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaxTokens) {
		toSerialize["max_tokens"] = o.MaxTokens
	}
	return toSerialize, nil
}

type NullableChunkIncludeOptions struct {
	value *ChunkIncludeOptions
	isSet bool
}

func (v NullableChunkIncludeOptions) Get() *ChunkIncludeOptions {
	return v.value
}

func (v *NullableChunkIncludeOptions) Set(val *ChunkIncludeOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableChunkIncludeOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableChunkIncludeOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChunkIncludeOptions(val *ChunkIncludeOptions) *NullableChunkIncludeOptions {
	return &NullableChunkIncludeOptions{value: val, isSet: true}
}

func (v NullableChunkIncludeOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChunkIncludeOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


