/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.7.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AsyncOperationSubmitResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AsyncOperationSubmitResponse{}

// AsyncOperationSubmitResponse Response model for submitting an async operation.
type AsyncOperationSubmitResponse struct {
	OperationId string `json:"operation_id"`
	Status string `json:"status"`
}

type _AsyncOperationSubmitResponse AsyncOperationSubmitResponse

// NewAsyncOperationSubmitResponse instantiates a new AsyncOperationSubmitResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAsyncOperationSubmitResponse(operationId string, status string) *AsyncOperationSubmitResponse {
	this := AsyncOperationSubmitResponse{}
	this.OperationId = operationId
	this.Status = status
	return &this
}

// NewAsyncOperationSubmitResponseWithDefaults instantiates a new AsyncOperationSubmitResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAsyncOperationSubmitResponseWithDefaults() *AsyncOperationSubmitResponse {
	this := AsyncOperationSubmitResponse{}
	return &this
}

// GetOperationId returns the OperationId field value
func (o *AsyncOperationSubmitResponse) GetOperationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationId
}

// GetOperationIdOk returns a tuple with the OperationId field value
// and a boolean to check if the value has been set.
func (o *AsyncOperationSubmitResponse) GetOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationId, true
}

// SetOperationId sets field value
func (o *AsyncOperationSubmitResponse) SetOperationId(v string) {
	o.OperationId = v
}

// GetStatus returns the Status field value
func (o *AsyncOperationSubmitResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AsyncOperationSubmitResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AsyncOperationSubmitResponse) SetStatus(v string) {
	o.Status = v
}

func (o AsyncOperationSubmitResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AsyncOperationSubmitResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operation_id"] = o.OperationId
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *AsyncOperationSubmitResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operation_id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAsyncOperationSubmitResponse := _AsyncOperationSubmitResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAsyncOperationSubmitResponse)

	if err != nil {
		return err
	}

	*o = AsyncOperationSubmitResponse(varAsyncOperationSubmitResponse)

	return err
}

type NullableAsyncOperationSubmitResponse struct {
	value *AsyncOperationSubmitResponse
	isSet bool
}

func (v NullableAsyncOperationSubmitResponse) Get() *AsyncOperationSubmitResponse {
	return v.value
}

func (v *NullableAsyncOperationSubmitResponse) Set(val *AsyncOperationSubmitResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAsyncOperationSubmitResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAsyncOperationSubmitResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAsyncOperationSubmitResponse(val *AsyncOperationSubmitResponse) *NullableAsyncOperationSubmitResponse {
	return &NullableAsyncOperationSubmitResponse{value: val, isSet: true}
}

func (v NullableAsyncOperationSubmitResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAsyncOperationSubmitResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


