/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.7.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the SourceFactsIncludeOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SourceFactsIncludeOptions{}

// SourceFactsIncludeOptions Options for including source facts for observation-type results.
type SourceFactsIncludeOptions struct {
	// Maximum total tokens for source facts across all observations (-1 = unlimited)
	MaxTokens *int32 `json:"max_tokens,omitempty"`
	// Maximum tokens of source facts per observation (-1 = unlimited)
	MaxTokensPerObservation *int32 `json:"max_tokens_per_observation,omitempty"`
}

// NewSourceFactsIncludeOptions instantiates a new SourceFactsIncludeOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourceFactsIncludeOptions() *SourceFactsIncludeOptions {
	this := SourceFactsIncludeOptions{}
	var maxTokens int32 = 4096
	this.MaxTokens = &maxTokens
	var maxTokensPerObservation int32 = -1
	this.MaxTokensPerObservation = &maxTokensPerObservation
	return &this
}

// NewSourceFactsIncludeOptionsWithDefaults instantiates a new SourceFactsIncludeOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceFactsIncludeOptionsWithDefaults() *SourceFactsIncludeOptions {
	this := SourceFactsIncludeOptions{}
	var maxTokens int32 = 4096
	this.MaxTokens = &maxTokens
	var maxTokensPerObservation int32 = -1
	this.MaxTokensPerObservation = &maxTokensPerObservation
	return &this
}

// GetMaxTokens returns the MaxTokens field value if set, zero value otherwise.
func (o *SourceFactsIncludeOptions) GetMaxTokens() int32 {
	if o == nil || IsNil(o.MaxTokens) {
		var ret int32
		return ret
	}
	return *o.MaxTokens
}

// GetMaxTokensOk returns a tuple with the MaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceFactsIncludeOptions) GetMaxTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxTokens) {
		return nil, false
	}
	return o.MaxTokens, true
}

// HasMaxTokens returns a boolean if a field has been set.
func (o *SourceFactsIncludeOptions) HasMaxTokens() bool {
	if o != nil && !IsNil(o.MaxTokens) {
		return true
	}

	return false
}

// SetMaxTokens gets a reference to the given int32 and assigns it to the MaxTokens field.
func (o *SourceFactsIncludeOptions) SetMaxTokens(v int32) {
	o.MaxTokens = &v
}

// GetMaxTokensPerObservation returns the MaxTokensPerObservation field value if set, zero value otherwise.
func (o *SourceFactsIncludeOptions) GetMaxTokensPerObservation() int32 {
	if o == nil || IsNil(o.MaxTokensPerObservation) {
		var ret int32
		return ret
	}
	return *o.MaxTokensPerObservation
}

// GetMaxTokensPerObservationOk returns a tuple with the MaxTokensPerObservation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceFactsIncludeOptions) GetMaxTokensPerObservationOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxTokensPerObservation) {
		return nil, false
	}
	return o.MaxTokensPerObservation, true
}

// HasMaxTokensPerObservation returns a boolean if a field has been set.
func (o *SourceFactsIncludeOptions) HasMaxTokensPerObservation() bool {
	if o != nil && !IsNil(o.MaxTokensPerObservation) {
		return true
	}

	return false
}

// SetMaxTokensPerObservation gets a reference to the given int32 and assigns it to the MaxTokensPerObservation field.
func (o *SourceFactsIncludeOptions) SetMaxTokensPerObservation(v int32) {
	o.MaxTokensPerObservation = &v
}

func (o SourceFactsIncludeOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SourceFactsIncludeOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaxTokens) {
		toSerialize["max_tokens"] = o.MaxTokens
	}
	if !IsNil(o.MaxTokensPerObservation) {
		toSerialize["max_tokens_per_observation"] = o.MaxTokensPerObservation
	}
	return toSerialize, nil
}

type NullableSourceFactsIncludeOptions struct {
	value *SourceFactsIncludeOptions
	isSet bool
}

func (v NullableSourceFactsIncludeOptions) Get() *SourceFactsIncludeOptions {
	return v.value
}

func (v *NullableSourceFactsIncludeOptions) Set(val *SourceFactsIncludeOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceFactsIncludeOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceFactsIncludeOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceFactsIncludeOptions(val *SourceFactsIncludeOptions) *NullableSourceFactsIncludeOptions {
	return &NullableSourceFactsIncludeOptions{value: val, isSet: true}
}

func (v NullableSourceFactsIncludeOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceFactsIncludeOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


