/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.7.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateDirectiveRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDirectiveRequest{}

// CreateDirectiveRequest Request model for creating a directive.
type CreateDirectiveRequest struct {
	// Human-readable name for the directive
	Name string `json:"name"`
	// The directive text to inject into prompts
	Content string `json:"content"`
	// Higher priority directives are injected first
	Priority *int32 `json:"priority,omitempty"`
	// Whether this directive is active
	IsActive *bool `json:"is_active,omitempty"`
	// Tags for filtering
	Tags []string `json:"tags,omitempty"`
}

type _CreateDirectiveRequest CreateDirectiveRequest

// NewCreateDirectiveRequest instantiates a new CreateDirectiveRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDirectiveRequest(name string, content string) *CreateDirectiveRequest {
	this := CreateDirectiveRequest{}
	this.Name = name
	this.Content = content
	var priority int32 = 0
	this.Priority = &priority
	var isActive bool = true
	this.IsActive = &isActive
	return &this
}

// NewCreateDirectiveRequestWithDefaults instantiates a new CreateDirectiveRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDirectiveRequestWithDefaults() *CreateDirectiveRequest {
	this := CreateDirectiveRequest{}
	var priority int32 = 0
	this.Priority = &priority
	var isActive bool = true
	this.IsActive = &isActive
	return &this
}

// GetName returns the Name field value
func (o *CreateDirectiveRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateDirectiveRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateDirectiveRequest) SetName(v string) {
	o.Name = v
}

// GetContent returns the Content field value
func (o *CreateDirectiveRequest) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *CreateDirectiveRequest) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *CreateDirectiveRequest) SetContent(v string) {
	o.Content = v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *CreateDirectiveRequest) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDirectiveRequest) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *CreateDirectiveRequest) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *CreateDirectiveRequest) SetPriority(v int32) {
	o.Priority = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *CreateDirectiveRequest) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDirectiveRequest) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *CreateDirectiveRequest) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *CreateDirectiveRequest) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CreateDirectiveRequest) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDirectiveRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CreateDirectiveRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *CreateDirectiveRequest) SetTags(v []string) {
	o.Tags = v
}

func (o CreateDirectiveRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDirectiveRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["content"] = o.Content
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

func (o *CreateDirectiveRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDirectiveRequest := _CreateDirectiveRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateDirectiveRequest)

	if err != nil {
		return err
	}

	*o = CreateDirectiveRequest(varCreateDirectiveRequest)

	return err
}

type NullableCreateDirectiveRequest struct {
	value *CreateDirectiveRequest
	isSet bool
}

func (v NullableCreateDirectiveRequest) Get() *CreateDirectiveRequest {
	return v.value
}

func (v *NullableCreateDirectiveRequest) Set(val *CreateDirectiveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDirectiveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDirectiveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDirectiveRequest(val *CreateDirectiveRequest) *NullableCreateDirectiveRequest {
	return &NullableCreateDirectiveRequest{value: val, isSet: true}
}

func (v NullableCreateDirectiveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDirectiveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


