/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.7.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BackgroundResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackgroundResponse{}

// BackgroundResponse Response model for background update. Deprecated: use MissionResponse instead.
type BackgroundResponse struct {
	Mission string `json:"mission"`
	Background NullableString `json:"background,omitempty"`
	Disposition NullableDispositionTraits `json:"disposition,omitempty"`
}

type _BackgroundResponse BackgroundResponse

// NewBackgroundResponse instantiates a new BackgroundResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackgroundResponse(mission string) *BackgroundResponse {
	this := BackgroundResponse{}
	this.Mission = mission
	return &this
}

// NewBackgroundResponseWithDefaults instantiates a new BackgroundResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackgroundResponseWithDefaults() *BackgroundResponse {
	this := BackgroundResponse{}
	return &this
}

// GetMission returns the Mission field value
func (o *BackgroundResponse) GetMission() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mission
}

// GetMissionOk returns a tuple with the Mission field value
// and a boolean to check if the value has been set.
func (o *BackgroundResponse) GetMissionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mission, true
}

// SetMission sets field value
func (o *BackgroundResponse) SetMission(v string) {
	o.Mission = v
}

// GetBackground returns the Background field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackgroundResponse) GetBackground() string {
	if o == nil || IsNil(o.Background.Get()) {
		var ret string
		return ret
	}
	return *o.Background.Get()
}

// GetBackgroundOk returns a tuple with the Background field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackgroundResponse) GetBackgroundOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Background.Get(), o.Background.IsSet()
}

// HasBackground returns a boolean if a field has been set.
func (o *BackgroundResponse) HasBackground() bool {
	if o != nil && o.Background.IsSet() {
		return true
	}

	return false
}

// SetBackground gets a reference to the given NullableString and assigns it to the Background field.
func (o *BackgroundResponse) SetBackground(v string) {
	o.Background.Set(&v)
}
// SetBackgroundNil sets the value for Background to be an explicit nil
func (o *BackgroundResponse) SetBackgroundNil() {
	o.Background.Set(nil)
}

// UnsetBackground ensures that no value is present for Background, not even an explicit nil
func (o *BackgroundResponse) UnsetBackground() {
	o.Background.Unset()
}

// GetDisposition returns the Disposition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackgroundResponse) GetDisposition() DispositionTraits {
	if o == nil || IsNil(o.Disposition.Get()) {
		var ret DispositionTraits
		return ret
	}
	return *o.Disposition.Get()
}

// GetDispositionOk returns a tuple with the Disposition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackgroundResponse) GetDispositionOk() (*DispositionTraits, bool) {
	if o == nil {
		return nil, false
	}
	return o.Disposition.Get(), o.Disposition.IsSet()
}

// HasDisposition returns a boolean if a field has been set.
func (o *BackgroundResponse) HasDisposition() bool {
	if o != nil && o.Disposition.IsSet() {
		return true
	}

	return false
}

// SetDisposition gets a reference to the given NullableDispositionTraits and assigns it to the Disposition field.
func (o *BackgroundResponse) SetDisposition(v DispositionTraits) {
	o.Disposition.Set(&v)
}
// SetDispositionNil sets the value for Disposition to be an explicit nil
func (o *BackgroundResponse) SetDispositionNil() {
	o.Disposition.Set(nil)
}

// UnsetDisposition ensures that no value is present for Disposition, not even an explicit nil
func (o *BackgroundResponse) UnsetDisposition() {
	o.Disposition.Unset()
}

func (o BackgroundResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackgroundResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mission"] = o.Mission
	if o.Background.IsSet() {
		toSerialize["background"] = o.Background.Get()
	}
	if o.Disposition.IsSet() {
		toSerialize["disposition"] = o.Disposition.Get()
	}
	return toSerialize, nil
}

func (o *BackgroundResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mission",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBackgroundResponse := _BackgroundResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBackgroundResponse)

	if err != nil {
		return err
	}

	*o = BackgroundResponse(varBackgroundResponse)

	return err
}

type NullableBackgroundResponse struct {
	value *BackgroundResponse
	isSet bool
}

func (v NullableBackgroundResponse) Get() *BackgroundResponse {
	return v.value
}

func (v *NullableBackgroundResponse) Set(val *BackgroundResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBackgroundResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBackgroundResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackgroundResponse(val *BackgroundResponse) *NullableBackgroundResponse {
	return &NullableBackgroundResponse{value: val, isSet: true}
}

func (v NullableBackgroundResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackgroundResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


