/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.7.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the EntityIncludeOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityIncludeOptions{}

// EntityIncludeOptions Options for including entity observations in recall results.
type EntityIncludeOptions struct {
	// Maximum tokens for entity observations
	MaxTokens *int32 `json:"max_tokens,omitempty"`
}

// NewEntityIncludeOptions instantiates a new EntityIncludeOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityIncludeOptions() *EntityIncludeOptions {
	this := EntityIncludeOptions{}
	var maxTokens int32 = 500
	this.MaxTokens = &maxTokens
	return &this
}

// NewEntityIncludeOptionsWithDefaults instantiates a new EntityIncludeOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityIncludeOptionsWithDefaults() *EntityIncludeOptions {
	this := EntityIncludeOptions{}
	var maxTokens int32 = 500
	this.MaxTokens = &maxTokens
	return &this
}

// GetMaxTokens returns the MaxTokens field value if set, zero value otherwise.
func (o *EntityIncludeOptions) GetMaxTokens() int32 {
	if o == nil || IsNil(o.MaxTokens) {
		var ret int32
		return ret
	}
	return *o.MaxTokens
}

// GetMaxTokensOk returns a tuple with the MaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityIncludeOptions) GetMaxTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxTokens) {
		return nil, false
	}
	return o.MaxTokens, true
}

// HasMaxTokens returns a boolean if a field has been set.
func (o *EntityIncludeOptions) HasMaxTokens() bool {
	if o != nil && !IsNil(o.MaxTokens) {
		return true
	}

	return false
}

// SetMaxTokens gets a reference to the given int32 and assigns it to the MaxTokens field.
func (o *EntityIncludeOptions) SetMaxTokens(v int32) {
	o.MaxTokens = &v
}

func (o EntityIncludeOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityIncludeOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaxTokens) {
		toSerialize["max_tokens"] = o.MaxTokens
	}
	return toSerialize, nil
}

type NullableEntityIncludeOptions struct {
	value *EntityIncludeOptions
	isSet bool
}

func (v NullableEntityIncludeOptions) Get() *EntityIncludeOptions {
	return v.value
}

func (v *NullableEntityIncludeOptions) Set(val *EntityIncludeOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityIncludeOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityIncludeOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityIncludeOptions(val *EntityIncludeOptions) *NullableEntityIncludeOptions {
	return &NullableEntityIncludeOptions{value: val, isSet: true}
}

func (v NullableEntityIncludeOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityIncludeOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


