/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.7.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EntityInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityInput{}

// EntityInput Entity to associate with retained content.
type EntityInput struct {
	// The entity name/text
	Text string `json:"text"`
	Type NullableString `json:"type,omitempty"`
}

type _EntityInput EntityInput

// NewEntityInput instantiates a new EntityInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityInput(text string) *EntityInput {
	this := EntityInput{}
	this.Text = text
	return &this
}

// NewEntityInputWithDefaults instantiates a new EntityInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityInputWithDefaults() *EntityInput {
	this := EntityInput{}
	return &this
}

// GetText returns the Text field value
func (o *EntityInput) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *EntityInput) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *EntityInput) SetText(v string) {
	o.Text = v
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EntityInput) GetType() string {
	if o == nil || IsNil(o.Type.Get()) {
		var ret string
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityInput) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *EntityInput) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableString and assigns it to the Type field.
func (o *EntityInput) SetType(v string) {
	o.Type.Set(&v)
}
// SetTypeNil sets the value for Type to be an explicit nil
func (o *EntityInput) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *EntityInput) UnsetType() {
	o.Type.Unset()
}

func (o EntityInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}
	return toSerialize, nil
}

func (o *EntityInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntityInput := _EntityInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEntityInput)

	if err != nil {
		return err
	}

	*o = EntityInput(varEntityInput)

	return err
}

type NullableEntityInput struct {
	value *EntityInput
	isSet bool
}

func (v NullableEntityInput) Get() *EntityInput {
	return v.value
}

func (v *NullableEntityInput) Set(val *EntityInput) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityInput) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityInput(val *EntityInput) *NullableEntityInput {
	return &NullableEntityInput{value: val, isSet: true}
}

func (v NullableEntityInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


