"""Workaround for Cursor's broken sessionStart ``additionalContext`` path.

Cursor's ``sessionStart`` hook accepts ``additionalContext`` JSON output but
silently drops it before the agent's composer handle is ready — a race
condition acknowledged by Cursor staff (Dean Rie, 2026-04-20 in forum thread
158452) and still present as of Cursor 3.6.31 (verified 2026-06-02). The
documented workaround is to write recalled memories to a workspace
``.cursor/rules/<name>.mdc`` file with ``alwaysApply: true``; the rules engine
reliably injects those into the agent's context.

This module isolates that fallback so ``session_start.py`` stays focused on
the recall flow itself. The hook still emits ``additionalContext`` to stdout
for forward-compat: when Cursor fixes the bug we drop the rules-file write
and the same plugin works on the cleaner native path.

Tracking the upstream bug:
https://forum.cursor.com/t/sessionstart-hook-additional-context-is-never-injected-into-agents-initial-system-context/158452
"""

from __future__ import annotations

import os
from typing import Callable, Optional

RULES_FILE_RELPATH = os.path.join(".cursor", "rules", "hindsight-session.mdc")
GITIGNORE_RELPATH = ".gitignore"
BUG_LINK = (
    "https://forum.cursor.com/t/sessionstart-hook-additional-context-is-never-"
    "injected-into-agents-initial-system-context/158452"
)
_GITIGNORE_LINE = "/" + RULES_FILE_RELPATH


def format_rule_content(memories_formatted: str, preamble: str, current_time: str) -> str:
    """Build the .mdc rules-file body with frontmatter + memory block.

    The frontmatter uses ``alwaysApply: true`` so Cursor injects the content
    into every agent turn within the workspace. The header comment makes the
    file obviously safe to delete if a user stumbles across it.
    """
    return (
        "---\n"
        "description: Session memories recalled by the Hindsight plugin. Safe to delete; will be regenerated.\n"
        "alwaysApply: true\n"
        "---\n\n"
        f"<!-- Generated by the hindsight-cursor sessionStart hook at {current_time}.\n"
        "     Workaround for Cursor's sessionStart additionalContext race condition:\n"
        f"     {BUG_LINK} -->\n\n"
        "<hindsight_memories>\n"
        f"{preamble}\n"
        f"Current time - {current_time}\n\n"
        f"{memories_formatted}\n"
        "</hindsight_memories>\n"
    )


def rotate_session_rules(
    workspace_root: Optional[str],
    debug_fn: Optional[Callable[[str], None]] = None,
) -> None:
    """Remove any prior session rules file so stale memories don't linger.

    Called at the top of every ``sessionStart`` invocation — if recall later
    returns nothing, the workspace ends up with no rules file rather than
    showing the previous session's memories.
    """
    if not workspace_root:
        return
    path = os.path.join(workspace_root, RULES_FILE_RELPATH)
    try:
        os.remove(path)
        if debug_fn:
            debug_fn(f"Removed stale session rules: {path}")
    except FileNotFoundError:
        pass
    except OSError as e:
        if debug_fn:
            debug_fn(f"Could not remove session rules at {path}: {e}")


def write_session_rules(
    workspace_root: Optional[str],
    content: str,
    debug_fn: Optional[Callable[[str], None]] = None,
) -> bool:
    """Write the rules file. Returns True on success, False on any failure."""
    if not workspace_root:
        return False
    path = os.path.join(workspace_root, RULES_FILE_RELPATH)
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        if debug_fn:
            debug_fn(f"Wrote session rules: {path}")
        return True
    except OSError as e:
        if debug_fn:
            debug_fn(f"Could not write session rules at {path}: {e}")
        return False


def ensure_gitignored(
    workspace_root: Optional[str],
    debug_fn: Optional[Callable[[str], None]] = None,
) -> bool:
    """Append the rules-file path to the workspace ``.gitignore`` if absent.

    No-op when the workspace is not a git repository (no ``.git`` entry) —
    the rules file is still useful there, just nothing to gitignore against.
    Idempotent: matches either ``/.cursor/rules/hindsight-session.mdc`` or
    the bare relative form. Returns True only when a line was appended.
    """
    if not workspace_root:
        return False
    git_marker = os.path.join(workspace_root, ".git")
    if not os.path.exists(git_marker):
        return False
    gitignore_path = os.path.join(workspace_root, GITIGNORE_RELPATH)
    try:
        existing = ""
        if os.path.exists(gitignore_path):
            with open(gitignore_path, encoding="utf-8") as f:
                existing = f.read()
        for raw in existing.splitlines():
            stripped = raw.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped in (_GITIGNORE_LINE, RULES_FILE_RELPATH):
                return False
        # Always start the block on a fresh line.
        sep = "" if existing == "" or existing.endswith("\n") else "\n"
        block = (
            f"{sep}\n# Added by hindsight-cursor plugin — session rules are regenerated each session.\n"
            f"{_GITIGNORE_LINE}\n"
        )
        with open(gitignore_path, "a", encoding="utf-8") as f:
            f.write(block)
        if debug_fn:
            debug_fn(f"Appended {_GITIGNORE_LINE} to {gitignore_path}")
        return True
    except OSError as e:
        if debug_fn:
            debug_fn(f"Could not update {gitignore_path}: {e}")
        return False
