"""Serialization schema for the document transfer archive (manifest + per-document payloads).

The archive is a ZIP:

    manifest.json              -- TransferManifest
    documents/000000.json      -- TransferDocument (one file per document)
    documents/000001.json
    ...

Documents are stored under a zero-padded index rather than their id so that
arbitrary document ids (which may contain path-unsafe characters) never leak
into archive entry names. The real id lives inside each payload.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

# Bump when the archive layout changes in a backward-incompatible way.
SCHEMA_VERSION = 1

ObservationScopes = Literal["per_tag", "combined", "all_combinations", "shared"] | list[list[str]]


class TransferCausalRelation(BaseModel):
    """A causal edge from this fact to an earlier fact in the same document.

    ``target_fact_index`` is the ordinal of the target fact within the document's
    ``facts`` list (not a database id), so it survives transfer to a new bank.
    """

    relation_type: str
    target_fact_index: int


class TransferFact(BaseModel):
    """One extracted fact (memory unit) without its embedding or database id.

    Everything here is reused verbatim on import except the embedding, which is
    regenerated by the target bank's model, and the entity ids, which are
    re-resolved against the target bank by canonical name.
    """

    text: str
    fact_type: str
    context: str | None = None
    # event_date is a fallback used only when both occurred_start and
    # mentioned_at are absent, to satisfy the NOT NULL event_date column.
    event_date: datetime | None = None
    occurred_start: datetime | None = None
    occurred_end: datetime | None = None
    mentioned_at: datetime | None = None
    metadata: dict[str, str] = Field(default_factory=dict)
    tags: list[str] = Field(default_factory=list)
    observation_scopes: ObservationScopes | None = None
    # Ordinal of the source chunk within the document (parsed from chunk_id).
    chunk_index: int | None = None
    # Entity canonical names; re-resolved against the target bank on import.
    entities: list[str] = Field(default_factory=list)
    causal_relations: list[TransferCausalRelation] = Field(default_factory=list)


class TransferChunk(BaseModel):
    """A raw text chunk of the source document, reused verbatim."""

    chunk_index: int
    chunk_text: str


class TransferObservationSource(BaseModel):
    """A reference to a source fact of an observation, by document + ordinal.

    Observations span documents and reference their source facts by unit id;
    those ids don't survive transfer, so each source is carried as the
    (document_id, fact_index) of the fact within the exported document set.
    """

    document_id: str
    fact_index: int


class TransferObservation(BaseModel):
    """A consolidated observation (``fact_type='observation'``).

    Observations are bank-level (not tied to one document), carry no embedding
    (re-generated on import) and no entity/link associations — retrieval reaches
    entities/links through their source facts. Only exported when explicitly
    requested, and only when every source resolves within the archive.
    """

    text: str
    tags: list[str] = Field(default_factory=list)
    event_date: datetime | None = None
    occurred_start: datetime | None = None
    occurred_end: datetime | None = None
    mentioned_at: datetime | None = None
    observation_scopes: ObservationScopes | None = None
    proof_count: int = 1
    sources: list[TransferObservationSource] = Field(default_factory=list)


class TransferDocument(BaseModel):
    """A single document plus its chunks and extracted facts."""

    id: str
    original_text: str | None = None
    retain_params: dict | None = None
    tags: list[str] = Field(default_factory=list)
    created_at: datetime | None = None
    chunks: list[TransferChunk] = Field(default_factory=list)
    facts: list[TransferFact] = Field(default_factory=list)


class TransferManifest(BaseModel):
    """Top-level archive descriptor (``manifest.json``).

    The bank-level fields default to a documents-only archive so older
    document-only archives (and the document import path) keep parsing
    unchanged; ``export_bank`` populates them for a whole-bank archive.
    """

    schema_version: int = SCHEMA_VERSION
    source_bank_id: str
    exported_at: datetime | None = None
    document_count: int = 0
    fact_count: int = 0
    observation_count: int = 0
    # "documents" = doc/fact/observation subset; "bank" = whole-bank export
    # (also carries bank config, mental models, directives, webhooks).
    archive_type: Literal["documents", "bank"] = "documents"
    mental_model_count: int = 0
    directive_count: int = 0
    webhook_count: int = 0
    # True when --include-history carried audit_log / llm_requests.
    includes_history: bool = False
